// This file is automatically generated by Firebase App Hosting.
// Do not edit this file manually.
export const firebaseConfig = {
  "apiKey": "AIzaSyDnqpDkmttNbyPcZadBKMOrPjZLSN0SNyo",
  "authDomain": "studio-4092189688-c74a7.firebaseapp.com",
  "projectId": "studio-4092189688-c74a7",
  "storageBucket": "studio-4092189688-c74a7.appspot.com",
  "messagingSenderId": "651059136924",
  "appId": "1:651059136924:web:0070ef26644101f9fb2059",
  "measurementId": "G-5G012E421F"
};
